version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 25
  return-statements:
    config:
      threshold: 10
  similar-code:
    enabled: true
  identical-code:
    enabled: true
